### ISSUE TITLE
Buildless flag releases

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-feature-flags-api#132]
Last night's build failures were a reminder that needing a build + preboot in order to toggle a flag is far from ideal.

I suggest we move to polling bertha. When a request for flags from Bertha is successful our tests are run against the response. If the flags fail tests then errors are sent to sentry/slack. When flags pass test they are saved to redis or some similar lightweight persistence and also held in memory. Flags served by the service are those held in memory if they exist, retrieving the last good set from redis if the bertha polling hasn't returned yet.

@matthew-andrews @commuterjoy

**Comment by wheresrhys** [comment]
or if we're confident enough of stale on error + preboot we could leave out redis

**Comment by matthew-andrews** [comment]
a simple quick solution could be that we could put the flags as a static json file on S3.

**Comment by matthew-andrews** [comment]
incidentally — this was causing the build failures last night @wheresrhys 
https://github.com/Financial-Times/next-feature-flags-api/commit/aff6155b48378ed600abed69b5899746d1f8841f

**Comment by wheresrhys** [comment]
We'd still need the tests to validate the JSON so would need some app as an intermediary, in which case  bertha seems like a good admin interface for generating the JSON

**Comment by matthew-andrews** [comment]
i was thinking something like next-assets so the workflow stays the same
https://github.com/Financial-Times/next-assets/blob/master/Makefile#L18

**Comment by wheresrhys** [comment]
hmm, the workflow is what I don't like about the current implementation, both the delay between deciding to toggle/add a flag and getting it into prod and the techiness of what often should be a product owner/admin task

**Comment by matthew-andrews** [comment]
if we used S3 you could deploy on command line much more reliably so it would be instant?

**Comment by matthew-andrews** [comment]
nbt also supports purging of fastly caches

**Comment by wheresrhys** [comment]
But then it's open to errors where someone has not pulled origin/master, and I still think 'ask a developer to do it' is an undesirable and unnecessary part of the workflow. 

A con of the bertha option is that google spreadsheets offer no safeguard against flags being deleted accidentally (but then again, neither does the current workflow)

**Comment by wheresrhys** [comment]
But S3 would be an improvement nonetheless and less work, so not too bothered about a better admin workflow for now.

**Comment by matthew-andrews** [comment]
compared with the flags API, so much value could be unlocked by backing the service registry onto a database (e.g. the ability to implement our own, better version of preboot; a way to do canaries / run our tests through the CDN securely).

overall, flags aint great but it's alright.  s3 could fix many (although not all) of the problems you've described but i feel if we're going to put time in to something like this i'd much rather spend time investing in the service registry.

**Comment by matthew-andrews** [comment]
@aintgoin2goa is going to work on this — flag in #293
